import {
  userPathsDocs,
  rolePathsDocs,
  userHasRolePathsDocs,
  postPathsDocs,
  tagPathsDocs,
  createTagPath,
  readAllTagsPath,
  filePathsDocs,
  externalFilePathsDocs,
  urlPathsDocs,
  readAllExternalFilesPath,
  externalFileByIdPath,
  createExternalFilePath,
  postHasAttachmentPathsDocs,
  postHasAttachmentByIdPath,
  readAllAttachmentsFromPostPath,
} from '@/main/docs/paths';

export default {
  ...userPathsDocs,
  ...rolePathsDocs,
  ...userHasRolePathsDocs,
  ...postPathsDocs,
  ...tagPathsDocs,
  '/tag': createTagPath,
  '/tag/all': readAllTagsPath,
  ...filePathsDocs,
  ...externalFilePathsDocs,
  '/attachment/external/file/all': readAllExternalFilesPath,
  '/attachment/external/file/{fileId}': externalFileByIdPath,
  '/attachment/external/file': createExternalFilePath,
  ...urlPathsDocs,
  ...postHasAttachmentPathsDocs,
  '/post/{postId}/attachment/all': readAllAttachmentsFromPostPath,
  '/post/{postId}/attachment/{attachmentId}': postHasAttachmentByIdPath,
};
