import {
  errorSchema,
  signUpParamsSchema,
  signInParamsSchema,
  userSchema,
  userUpdadeParamsSchema,
  verifyResetUserPasswordTokenParamsSchema,
  roleSchema,
  createRoleParamsSchema,
  userHasRoleSchema,
  userCritialDataSchema,
  postSchema,
  createPostParamsSchema,
  fileSchema,
  fileFormatSchema,
  fileTypeSchema,
  uploadFileParamsSchema,
  urlSchema,
  createUrlParamsSchema,
} from '@/main/docs/schemas';

export default {
  user: userSchema,
  signInParams: signInParamsSchema,
  signUpParams: signUpParamsSchema,
  error: errorSchema,
  userUpdadeParams: userUpdadeParamsSchema,
  verifyResetUserPasswordTokenParams: verifyResetUserPasswordTokenParamsSchema,
  role: roleSchema,
  createRoleParams: createRoleParamsSchema,
  userHasRole: userHasRoleSchema,
  userCritialData: userCritialDataSchema,
  post: postSchema,
  createPostParams: createPostParamsSchema,
  file: fileSchema,
  fileFormat: fileFormatSchema,
  fileType: fileTypeSchema,
  uploadFileParams: uploadFileParamsSchema,
  url: urlSchema,
  createUrlParams: createUrlParamsSchema,
};
